# Generated by Django 2.0 on 2019-05-30 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='executive',
            name='employee_id',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='executive',
            name='first_name',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='executive',
            name='last_name',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
