# Generated by Django 2.0 on 2019-06-19 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20190530_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='executive',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='executive',
            name='phone',
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
