# Generated by Django 2.0 on 2019-06-08 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('direct_or_extension', models.CharField(blank=True, max_length=16)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('company', models.CharField(blank=True, max_length=128)),
                ('emp_size', models.CharField(blank=True, max_length=16)),
                ('website', models.CharField(blank=True, max_length=64)),
                ('job_title', models.CharField(blank=True, max_length=64)),
                ('industry_type', models.CharField(blank=True, max_length=64)),
                ('city', models.CharField(blank=True, max_length=32)),
                ('state', models.CharField(blank=True, max_length=32)),
                ('country', models.CharField(blank=True, max_length=32)),
                ('zip_code', models.IntegerField(blank=True, null=True)),
                ('details', models.TextField(blank=True)),
            ],
        ),
    ]
