# Generated by Django 2.2.3 on 2019-08-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='zip_code',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
