# Generated by Django 2.2.3 on 2019-08-03 07:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0002_auto_20190801_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prospect',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
