# Generated by Django 2.2.3 on 2019-08-03 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaigns', '0002_auto_20190801_1216'),
        ('prospects', '0003_auto_20190803_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProspectUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('direct_or_extension', models.CharField(blank=True, max_length=16)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('job_title', models.CharField(blank=True, max_length=64)),
                ('company', models.CharField(blank=True, max_length=128)),
                ('emp_size', models.CharField(blank=True, max_length=16)),
                ('website', models.CharField(blank=True, max_length=64)),
                ('industry_type', models.CharField(blank=True, max_length=64)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('prospect_campaign_relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.ProspectCampaignRelation')),
            ],
        ),
    ]
