# Generated by Django 2.0 on 2019-06-08 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prospects', '0001_initial'),
        ('portal', '0002_auto_20190530_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('script', models.TextField(blank=True)),
                ('details', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True)),
                ('end_date', models.DateField(blank=True)),
                ('executives', models.ManyToManyField(blank=True, to='portal.Executive')),
            ],
        ),
        migrations.CreateModel(
            name='ProspectCampaignRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(auto_now_add=True)),
                ('attempted', models.BooleanField(default=False)),
                ('details', models.TextField(blank=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.Campaign')),
                ('prospect', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='prospects.Prospect')),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='prospects',
            field=models.ManyToManyField(blank=True, through='campaigns.ProspectCampaignRelation', to='prospects.Prospect'),
        ),
        migrations.AlterUniqueTogether(
            name='prospectcampaignrelation',
            unique_together={('prospect', 'campaign')},
        ),
    ]
