# Generated by Django 2.2.3 on 2019-08-01 06:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prospects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='executives',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaign',
            name='prospects',
            field=models.ManyToManyField(blank=True, through='campaigns.ProspectCampaignRelation', to='prospects.Prospect'),
        ),
        migrations.AlterUniqueTogether(
            name='prospectcampaignrelation',
            unique_together={('prospect', 'campaign')},
        ),
    ]
