# Generated by Django 2.0 on 2019-07-11 09:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_campaign_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 7, 11, 9, 39, 1, 535603, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
